server:
  port: 8087


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/