server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Silu@2001
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

